# Generated by Django 3.2.13 on 2024-07-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('sex', models.BooleanField(default=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'testing_members',
            },
        ),
    ]
