# Generated by Django 3.2.13 on 2024-07-29 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=30)),
                ('face', models.CharField(default='4e701907jw1e8qgp5bmzyj2050050aa8.jpg', max_length=50)),
                ('article_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowbase_author_basic_info',
                'ordering': ['-article_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=30)),
                ('integral', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowbase_author_level',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('article_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowbase_category',
                'ordering': ['-sort_order', '-article_number'],
            },
        ),
        migrations.CreateModel(
            name='AuthorDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=50)),
                ('gender', models.BooleanField(default=False)),
                ('birthday', models.DateField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.authorbasicinfo')),
            ],
            options={
                'db_table': 'knowbase_author_detail_info',
            },
        ),
        migrations.AddField(
            model_name='authorbasicinfo',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.authorlevel'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.authorbasicinfo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'db_table': 'knowbase_article',
                'ordering': ['-created_at', '-is_deleted'],
            },
        ),
    ]
