# Generated by Django 3.2.13 on 2024-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=250)),
                ('imageurl', models.CharField(max_length=80)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('publishing', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'testing_book',
            },
        ),
    ]
