"""
Django settings for dadashop project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-kkdjdq5usaf@z9m=h8u%=th596b)vc^_yo#tlxnclob)s02ozb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'goods',
    'carts',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dadashop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dadashop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': '123456',
        'NAME': 'dadashop',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media/'

####################CORS配置开始##########################

# 是否允许所有域进行跨域访问
CORS_ALLOW_ALL_ORIGINS = False

# 允许特定的源进行跨域访问
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:7000',
    'http://localhost:7000',
]

# 允许跨域访问时的请求方式
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

# 允许跨域访问时的请求头
CORS_ALLOW_HEADERS = (
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

#####################CORS配置结束#########################

#####################邮件服务器配置开始#####################

# 邮件服务器的后端
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 邮件服务器的地址
EMAIL_HOST = 'smtp.qq.com'

# 邮件服务器的用户名
EMAIL_HOST_USER = '184138029@qq.com'

# 邮件服务器使用的密码
EMAIL_HOST_PASSWORD = 'jhimokuwhkamcbaf'

#####################邮件服务器配置结束######################

#####################Redis缓存的配置开始#####################

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    },
    'sms': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    },
    'carts': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    }

}

#####################Redis缓存的配置结束#####################

#####################手机短信平台配置开始#####################

SMS_ACCOUNT_ID = '2c94811c8a27cf2d018a9814bd2520a1'

SMS_ACCOUNT_TOKEN = 'c2d4ee98fafd41bab4bb4689ceaaf0c0'

SMS_APP_ID = '2c94811c8a27cf2d018a9814be3120a8'

#####################手机短信平台配置结束#####################

#####################JWT密钥#####################

JWT_SECRET_KEY = '@&(XlP4xT6'

#####################JWT密钥#####################

#####################新浪微博的配置开始#####################

WEIBO_APP_ID = '3103796738'

WEIBO_APP_SECRET_KEY = '4c67b8542adf21cb605ff4add41e019c'

WEIBO_CALLBACK_URI = 'http://127.0.0.1:7000/dadashop/templates/callback.html'

#####################新浪微博的配置结束#####################

#####################媒体文件的路径开始#####################


DADASHOP_MEDIA_URL = 'http://127.0.0.1:8000/media/'

#####################媒体文件的路径结束#####################
