# Generated by Django 3.2.13 on 2024-08-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aricle',
            new_name='Article',
        ),
    ]
