USE words;

CREATE TABLE author(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE category(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE KEY
);

CREATE TABLE article(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	subject VARCHAR(80) NOT NULL,
	context MEDIUMTEXT NOT NULL,
	author_id INT UNSIGNED NOT NULL COMMENT '外键,作者ID',
	category_id INT UNSIGNED NOT NULL COMMENT '外键,分类ID',
	is_deleted BOOLEAN NOT NULL DEFAULT 0 '是否被删除'
);