# Generated by Django 3.2.13 on 2023-11-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=32)),
                ('sex', models.BooleanField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=22)),
            ],
            options={
                'db_table': 'testing_member',
            },
        ),
    ]
